### ISSUE TITLE
Can't access on iPhone7 - all browers

### ISSUE THREAD

**Issue by dwightmwilson** [DemocracyEarth/sovereign#166] opened 2017-04-28 19:44 UTC
not working on Chrome, Safari, Firefox - i do get a home screen of sorts (see comment below) but can't go further

**Comment by domi41** [comment] 2017-09-14 21:34
Duplicate of #155 and #159
Thanks for reporting, though ;)
Goes to show how critical that issue is.

**Closed by domi41** 2017-09-14 21:34 UTC
Labels: Type: Bug, Type: Duplicate
