### ISSUE TITLE
Login controls are not displayed in Firefox

### ISSUE THREAD

**Issue by thomfresn** [DemocracyEarth/sovereign#231] opened 2018-02-05 14:11 UTC
# This is a Bug Report 

#### :tophat: Description

* What went wrong?
 
When clicking on the identification button 
![image](https://user-images.githubusercontent.com/31652551/35808621-b3b0e108-0a86-11e8-9ff1-beb0dbad13ce.png)
, login controls are not always displayed

* What did you expect should have happened?

I expected to see the following controls: 
![image](https://user-images.githubusercontent.com/31652551/35808583-8ed7a6f0-0a86-11e8-9880-d2260af0ff90.png)

* What was the config you used?

Windows 10 64 bits
npm 5.6.0
Firefox 58.0.1

* What stacktrace or error message from your provider did you see?

#### :clipboard: Additional Data

* ***Sovereign deployment where you found the issue***:
 
commit 0b369a2f33c7a0b9b77e904264a1402cb4e596aa

* ***Browser & version***:

 Firefox 58.0.1

* ***Error messages***:

I don't seem to have any Javascript error when clicking on the identification button

**Comment by thomfresn** [comment] 2018-02-19 14:45
Just had a quick look at the issue, and found some weird values in earth.css for the popup style class (applied to the login popup)

- the top margin defined is set to -10000px

- the opacity is set to 0 (the element is therefore invisible)

I don't know how Chrome handles this but that may be the reasons I have display issues with Firefox.

**Comment by domi41** [comment] 2018-03-02 19:29
Noting that with current master, I can't reproduce the issue on Firefox 58.0.2 on Linux.

**Comment by virgile-dev** [comment] 2018-03-03 10:43
Haven't been able to reproduce it on Firefox either. It looks this has been fixed. I'm closing this for now.

**Closed** 2018-03-03 10:44 UTC
Labels: Browser: Firefox, Type: Bug

**Comment by patricktr** [comment] 2019-06-20 19:23
This seems to be back. When I click the login button on firefox, the button changes from purple to translucent, but otherwise no box opens up like it does with chrome and brave. Completely unable to log in using Firefox.
