### ISSUE TITLE
Convert hyperlinks in proposals' descriptions

### ISSUE THREAD

**Issue by SFSandra** [DemocracyEarth/sovereign#179] opened 2017-05-08 21:18 UTC
![image](https://cloud.githubusercontent.com/assets/24529258/25825815/3ad3e49c-33f9-11e7-9a0f-27345b1fdd25.png)

**Comment by domi41** [comment] 2017-09-14 22:11
We should support markdown, more generally, no ?

**Comment by domi41** [comment] 2017-09-15 14:15
This is somewhat a duplicate of #127

**Closed** 2018-03-03 11:01 UTC
Labels: Category: UX, Priority: High, Status: Help Wanted, Type: Enhancement
